name: 'Hello World JS Action by Leon Feng'
description: 'Greet someone and record the time'
author: 'Leon Feng'
icon: 'activity'
color: 'gray-dark'
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time:
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'index.js'
